name: CI-CD

on: push

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------
      # 1. Checkout Code
      # ------------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # 2. Setup Python 3.11
      # ------------------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # ------------------------------------------------------
      # 3. Install dependencies for CI testing
      # ------------------------------------------------------
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement_action.txt

      # ------------------------------------------------------
      # 4. Configure AWS Credentials for DVC (Account A)
      # ------------------------------------------------------
      - name: Configure AWS Credentials for DVC (Account A)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          # Account A (for DVC)
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Account A
          aws-region: eu-north-1

      # ------------------------------------------------------
      # 5. Pull data from S3 using DVC
      # ------------------------------------------------------
      - name: DVC Pull from S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc pull

      # ------------------------------------------------------
      # 6. Test MLflow Model Loading
      # ------------------------------------------------------
      - name: Test Model Loading
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          pytest tests/test_model_loading.py -q

      # ------------------------------------------------------
      # 7. Test Model Performance
      # ------------------------------------------------------
      - name: Test Model Performance
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          pytest tests/test_performance.py -q



      # ------------------------------------------------------
      # 8. Configure AWS FOR ECR + CodeDeploy (ACCOUNT B)
      # ------------------------------------------------------
      - name: Configure AWS Credentials (Account B)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_B }}         # Account B
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_B }} # Account B
          aws-region: eu-north-1


      # ------------------------------------------------------
      # 9. Login to Amazon ECR (ACCOUNT B)
      # ------------------------------------------------------
      - name: Login to Amazon ECR (Account B)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # ------------------------------------------------------
      # 10. Build, Tag, Push Docker Image to ECR (ACCOUNT B)
      # ------------------------------------------------------
      - name: Build, Tag, and Push Docker image to ECR (Account B)
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: delivery-time-estimator
          IMAGE_TAG: latest
        run: |
          echo "üèó Building Docker image..."
          docker build -t $REPOSITORY .

          echo "üè∑ Tagging image..."
          docker tag $REPOSITORY:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG

          echo "üì§ Pushing image to ECR..."
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          echo "‚úÖ Docker image pushed successfully!"



